# Generated by Django 4.1.3 on 2025-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_client_rating_profile_client_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/address_proof/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/id_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification/id_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification/passport/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='verification/selfies/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment/qr_codes/'),
        ),
    ]
