# Generated by Django 4.1.3 on 2025-04-05 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contract'),
        ('users', '0003_profile_address_proof_profile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerReview',
            fields=[
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('requirements', models.IntegerField(default=5)),
                ('communication', models.IntegerField(default=5)),
                ('payment', models.IntegerField(default=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_reviews', to='users.profile')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_reviews', to='projects.contract')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given_as_freelancer', to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('reviewer', 'client', 'contract')},
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('quality', models.IntegerField(default=5)),
                ('communication', models.IntegerField(default=5)),
                ('deadlines', models.IntegerField(default=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_reviews', to='projects.contract')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='users.profile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given_as_client', to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('reviewer', 'freelancer', 'contract')},
            },
        ),
    ]
