# Generated by Django 4.1.3 on 2025-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Estimated duration in days', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project price', max_digits=10, null=True),
        ),
    ]
