# Generated by Django 4.1.3 on 2025-04-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_duration_project_project_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_price',
        ),
    ]
